### ISSUE TITLE
Broken after first usage

### ISSUE THREAD

**Issue by Michel73** [marclipovsky/vscode-string-manipulation#7]
I used `swap case` and it works as it should. But after first usage it doesn't works until the workbench will be restarted.
VSCode version:  1.18.0
OS: Ubuntu 16.04

**Comment by ug0** [comment]
@marclipovsky I have the same issue. It works at first. But after that if I open another file, any transformation won't work on that file.

VSCode version: 1.25.1
OS: Ubuntu 16.04

Here are the log output in the console:
> workbench.main.js:sourcemap:1375  INFO no standard startup: not a new window
workbench.main.js:sourcemap:4103 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///usr/share/code/resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///home/u/.vscode/extensions/ms-mssql.mssql-1.4.0/syntaxes/SQL.plist
e.register @ workbench.main.js:sourcemap:4103
t._handleGrammarExtensionPointUser @ workbench.main.js:sourcemap:4107
(anonymous) @ workbench.main.js:sourcemap:4104
e._handle @ workbench.main.js:sourcemap:2916
e.acceptUsers @ workbench.main.js:sourcemap:2916
w._handleExtensionPoint @ workbench.main.js:sourcemap:3148
(anonymous) @ workbench.main.js:sourcemap:3139
g @ workbench.main.js:sourcemap:150
enter @ workbench.main.js:sourcemap:154
_run @ workbench.main.js:sourcemap:155
_completed @ workbench.main.js:sourcemap:155
then @ workbench.main.js:sourcemap:157
enter @ workbench.main.js:sourcemap:153
_run @ workbench.main.js:sourcemap:155
_setCompleteValue @ workbench.main.js:sourcemap:155
g @ workbench.main.js:sourcemap:150
enter @ workbench.main.js:sourcemap:154
_run @ workbench.main.js:sourcemap:155
_completed @ workbench.main.js:sourcemap:155
l @ workbench.main.js:sourcemap:158
n.Class.derive.join.r.forEach.j.then.o.(anonymous function) @ workbench.main.js:sourcemap:159
g @ workbench.main.js:sourcemap:150
enter @ workbench.main.js:sourcemap:154
_run @ workbench.main.js:sourcemap:155
_completed @ workbench.main.js:sourcemap:155
c @ workbench.main.js:sourcemap:160
s @ workbench.main.js:sourcemap:160
g @ workbench.main.js:sourcemap:150
enter @ workbench.main.js:sourcemap:154
_run @ workbench.main.js:sourcemap:155
_completed @ workbench.main.js:sourcemap:155
g @ workbench.main.js:sourcemap:150
enter @ workbench.main.js:sourcemap:154
_run @ workbench.main.js:sourcemap:155
_completed @ workbench.main.js:sourcemap:155
c @ workbench.main.js:sourcemap:160
s @ workbench.main.js:sourcemap:160
g @ workbench.main.js:sourcemap:150
enter @ workbench.main.js:sourcemap:154
_run @ workbench.main.js:sourcemap:155
_completed @ workbench.main.js:sourcemap:155
g @ workbench.main.js:sourcemap:150
enter @ workbench.main.js:sourcemap:154
_run @ workbench.main.js:sourcemap:155
_completed @ workbench.main.js:sourcemap:155
(anonymous) @ workbench.main.js:sourcemap:199
(anonymous) @ /usr/share/code/resources/app/node_modules.asar/graceful-fs/graceful-fs.js:78
tryToString @ original-fs.js:449
readFileAfterClose @ original-fs.js:436
workbench.main.js:sourcemap:4103 Overwriting grammar scope name to file mapping for scope source.ruby.
Old grammar file: file:///usr/share/code/resources/app/extensions/ruby/syntaxes/ruby.tmLanguage.json.
New grammar file: file:///home/u/.vscode/extensions/rebornix.ruby-0.18.0/syntaxes/ruby.cson.json
e.register @ workbench.main.js:sourcemap:4103
t._handleGrammarExtensionPointUser @ workbench.main.js:sourcemap:4107
(anonymous) @ workbench.main.js:sourcemap:4104
e._handle @ workbench.main.js:sourcemap:2916
e.acceptUsers @ workbench.main.js:sourcemap:2916
w._handleExtensionPoint @ workbench.main.js:sourcemap:3148
(anonymous) @ workbench.main.js:sourcemap:3139
g @ workbench.main.js:sourcemap:150
enter @ workbench.main.js:sourcemap:154
_run @ workbench.main.js:sourcemap:155
_completed @ workbench.main.js:sourcemap:155
then @ workbench.main.js:sourcemap:157
enter @ workbench.main.js:sourcemap:153
_run @ workbench.main.js:sourcemap:155
_setCompleteValue @ workbench.main.js:sourcemap:155
g @ workbench.main.js:sourcemap:150
enter @ workbench.main.js:sourcemap:154
_run @ workbench.main.js:sourcemap:155
_completed @ workbench.main.js:sourcemap:155
l @ workbench.main.js:sourcemap:158
n.Class.derive.join.r.forEach.j.then.o.(anonymous function) @ workbench.main.js:sourcemap:159
g @ workbench.main.js:sourcemap:150
enter @ workbench.main.js:sourcemap:154
_run @ workbench.main.js:sourcemap:155
_completed @ workbench.main.js:sourcemap:155
c @ workbench.main.js:sourcemap:160
s @ workbench.main.js:sourcemap:160
g @ workbench.main.js:sourcemap:150
enter @ workbench.main.js:sourcemap:154
_run @ workbench.main.js:sourcemap:155
_completed @ workbench.main.js:sourcemap:155
g @ workbench.main.js:sourcemap:150
enter @ workbench.main.js:sourcemap:154
_run @ workbench.main.js:sourcemap:155
_completed @ workbench.main.js:sourcemap:155
c @ workbench.main.js:sourcemap:160
s @ workbench.main.js:sourcemap:160
g @ workbench.main.js:sourcemap:150
enter @ workbench.main.js:sourcemap:154
_run @ workbench.main.js:sourcemap:155
_completed @ workbench.main.js:sourcemap:155
g @ workbench.main.js:sourcemap:150
enter @ workbench.main.js:sourcemap:154
_run @ workbench.main.js:sourcemap:155
_completed @ workbench.main.js:sourcemap:155
(anonymous) @ workbench.main.js:sourcemap:199
(anonymous) @ /usr/share/code/resources/app/node_modules.asar/graceful-fs/graceful-fs.js:78
tryToString @ original-fs.js:449
readFileAfterClose @ original-fs.js:436
workbench.main.js:sourcemap:1375  INFO No grammar found for scope source.graphql
workbench.main.js:sourcemap:1375  INFO No grammar found for scope source.js.jquery
workbench.main.js:sourcemap:1375  INFO No grammar found for scope source.smarty
workbench.main.js:sourcemap:1375  INFO No grammar found for scope source.applescript
workbench.main.js:sourcemap:1375  INFO No grammar found for scope text.html.textile
workbench.main.js:sourcemap:1375  INFO No grammar found for scope text.html.javadoc
workbench.main.js:sourcemap:1375  INFO No grammar found for scope source.dosbatch
workbench.main.js:sourcemap:1375  INFO No grammar found for scope source.scala
workbench.main.js:sourcemap:1375  INFO No grammar found for scope source.dart
workbench.main.js:sourcemap:1375  INFO No grammar found for scope source.postscript
workbench.main.js:sourcemap:1375  INFO No grammar found for scope source.sass
workbench.main.js:sourcemap:1375  INFO No grammar found for scope source.less
workbench.main.js:sourcemap:1375  INFO No grammar found for scope source.stylus
workbench.main.js:sourcemap:270 [Extension Host] WARNING: Promise with no error callback:2
workbench.main.js:sourcemap:270 [Extension Host]% Object {exception: null, error: Object, promise: Object, id: 2}
workbench.main.js:sourcemap:3150 [marclipovsky.string-manipulation]TextEditor#edit not possible on closed editors
e.$onExtensionRuntimeError @ workbench.main.js:sourcemap:3150
e._doInvokeHandler @ workbench.main.js:sourcemap:3127
e._invokeHandler @ workbench.main.js:sourcemap:3127
e._receiveRequest @ workbench.main.js:sourcemap:3126
e._receiveOneMessage @ workbench.main.js:sourcemap:3126
(anonymous) @ workbench.main.js:sourcemap:3125
(anonymous) @ workbench.main.js:sourcemap:3128
e.fire @ workbench.main.js:sourcemap:171
c @ workbench.main.js:sourcemap:302
(anonymous) @ workbench.main.js:sourcemap:303
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
workbench.main.js:sourcemap:3150 Error: TextEditor#edit not possible on closed editors
	at e.edit (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:750:725)
	at holder (/home/u/.vscode/extensions/marclipovsky.string-manipulation-0.2.0/extension.js:26:12)
	at /home/u/.vscode/extensions/marclipovsky.string-manipulation-0.2.0/extension.js:68:111
	at e._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:697:706)
	at e.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:698:212)
	at e._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:87)
	at e._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:657:779)
	at e._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:656:851)
	at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:656:620)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:655:544
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:673
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:96:599
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:97:917)
	at u (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:159:721)
	at Socket.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:159:898)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
e.$onExtensionRuntimeError @ workbench.main.js:sourcemap:3150
e._doInvokeHandler @ workbench.main.js:sourcemap:3127
e._invokeHandler @ workbench.main.js:sourcemap:3127
e._receiveRequest @ workbench.main.js:sourcemap:3126
e._receiveOneMessage @ workbench.main.js:sourcemap:3126
(anonymous) @ workbench.main.js:sourcemap:3125
(anonymous) @ workbench.main.js:sourcemap:3128
e.fire @ workbench.main.js:sourcemap:171
c @ workbench.main.js:sourcemap:302
(anonymous) @ workbench.main.js:sourcemap:303
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560

I'll also list the extensions I installed hope this will be more help:

- hjleochen.rails-nav-0.0.3
- hookyqr.beautify-1.3.2
- jakebecker.elixir-ls-0.2.21
- jithurjacob.nbpreviewer-1.0.0
- kkalita.dark-plus-elixir-0.1.1
- marclipovsky.string-manipulation-0.2.0
- mechatroner.rainbow-csv-0.4.2
- mikestead.dotenv-1.0.1
- ms-mssql.mssql-1.4.0
- ms-python.python-2018.7.1
- octref.vetur-0.12.5
- rebornix.ruby-0.18.0
- sammkj.vscode-elixir-formatter-0.2.0
- shardulm94.trailing-spaces-0.2.11
- stefanjarina.vscode-eex-snippets-0.0.3
- vscodevim.vim-0.15.7
- yzhang.markdown-all-in-one-1.6.0
- zimplexing.vartypes-0.0.1
-

**Comment by PapsOu** [comment]
@marclipovsky : Do you have any news about this bug ?

**Comment by Michel73** [comment]
It happens again. Version 1.27.2, OS: Ubuntu 16.
I tried `camelize` operation.
```
mainThreadExtensionService.ts:44 Error: TextEditor#edit not possible on closed editors
	at e.edit (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:780:348)
	at stringFunction (/home/vagrant/.vscode/extensions/marclipovsky.string-manipulation-0.3.1/extension.js:38:10)
	at context.subscriptions.push.commands.registerCommand (/home/vagrant/.vscode/extensions/marclipovsky.string-manipulation-0.3.1/extension.js:55:101)
	at e._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:726:706)
	at e.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:727:212)
	at e._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:681:309)
	at e._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:681:27)
	at e._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:679:802)
	at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:678:993)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:677:791
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:597
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:99:917)
	at a (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:164:787)
	at Socket._socketDataListener (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Comment by nejsimon** [comment]
I got this as well. OSX / Code 1.31.1. I used camelize on some strings and it worked but then it just stopped working. Thanks for a great extension btw!

`mainThreadExtensionService.ts:47 Error: TextEditor#edit not possible on closed editors
	at e.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:458)
	at stringFunction (/Users/simonstrandman/.vscode/extensions/marclipovsky.string-manipulation-0.3.1/extension.js:38)
	at exports.activate.Object.keys.forEach.context.subscriptions.push.commands.registerCommand (/Users/simonstrandman/.vscode/extensions/marclipovsky.string-manipulation-0.3.1/extension.js:55)
	at e._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:485)
	at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:486)
	at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:644)
	at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:643)
	at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642)
	at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:641)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:638
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:38
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170)
	at Socket.f._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170)
	at Socket.emit (events.js:182)
	at addChunk (_stream_readable.js:279)
	at readableAddChunk (_stream_readable.js:264)
	at Socket.Readable.push (_stream_readable.js:219)
	at Pipe.onread (net.js:636)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:47
t._doInvokeHandler @ rpcProtocol.ts:390
t._invokeHandler @ rpcProtocol.ts:375
t._receiveRequest @ rpcProtocol.ts:295
t._receiveOneMessage @ rpcProtocol.ts:225
(anonymous) @ rpcProtocol.ts:100
e.fire @ event.ts:567
s @ ipc.net.ts:295
(anonymous) @ ipc.net.ts:302
e.fire @ event.ts:567
a @ ipc.net.ts:103
_socketDataListener @ ipc.net.ts:132
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636`
