### ISSUE TITLE
Error Text Editor not possible on closed editors.

### ISSUE THREAD

**Issue by scrawfor** [marclipovsky/vscode-string-manipulation#9]
When trying to manipulate any string I get this error.

```
[Extension Host] WARNING: Promise with no error callback:15
log.ts:171   ERR TextEditor#edit not possible on closed editors: Error: TextEditor#edit not possible on closed editors
    at e.edit (c:\Users\scrawfor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:780:348)
    at stringFunction (C:\Users\scrawfor\.vscode\extensions\marclipovsky.string-manipulation-0.3.1\extension.js:38:10)
    at context.subscriptions.push.commands.registerCommand (C:\Users\scrawfor\.vscode\extensions\marclipovsky.string-manipulation-0.3.1\extension.js:55:101)
    at e._executeContributedCommand (c:\Users\scrawfor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:726:706)
    at e.$executeContributedCommand (c:\Users\scrawfor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:727:212)
    at e._doInvokeHandler (c:\Users\scrawfor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:309)
    at e._invokeHandler (c:\Users\scrawfor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:27)
    at e._receiveRequest (c:\Users\scrawfor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:679:802)
    at e._receiveOneMessage (c:\Users\scrawfor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:678:993)
    at c:\Users\scrawfor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:791
    at c:\Users\scrawfor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:597
    at e.fire (c:\Users\scrawfor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
    at a (c:\Users\scrawfor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:787)
    at Socket._socketDataListener (c:\Users\scrawfor\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:1006)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
console.ts:136 [Extension Host]% {exception: null, error: {…}, promise: {…}, id: 15}
```

**Comment by marclipovsky** [comment]
I am on vacation and will investigate as soon as I am able.

**Comment by whren** [comment]
Same problem here.
Workaround for me war to disable the extension, then do a reload, next re-activate the extension and finally a last reload.

**Comment by alexsomesan** [comment]
+1 I'm running into the issue as well.
On latest VSCode, the workaround only works for a single string operation, then it goes back to not working.

**Comment by marclipovsky** [comment]
Very sorry I'm still on parental leave until early December. I'll get this resolved as soon as I can when I'm back.

**Comment by alexsomesan** [comment]
No worries!
Congratulations for the little one! 🍼

**Comment by nejsimon** [comment]
I got this as well. OSX / Code 1.31.1. I used camelize on some strings and it worked but then it just stopped working.

`mainThreadExtensionService.ts:47 Error: TextEditor#edit not possible on closed editors
	at e.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:458)
	at stringFunction (/Users/simonstrandman/.vscode/extensions/marclipovsky.string-manipulation-0.3.1/extension.js:38)
	at exports.activate.Object.keys.forEach.context.subscriptions.push.commands.registerCommand (/Users/simonstrandman/.vscode/extensions/marclipovsky.string-manipulation-0.3.1/extension.js:55)
	at e._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:485)
	at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:486)
	at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:644)
	at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:643)
	at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642)
	at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:641)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:638
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:38
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44)
	at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170)
	at Socket.f._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:170)
	at Socket.emit (events.js:182)
	at addChunk (_stream_readable.js:279)
	at readableAddChunk (_stream_readable.js:264)
	at Socket.Readable.push (_stream_readable.js:219)
	at Pipe.onread (net.js:636)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:47
t._doInvokeHandler @ rpcProtocol.ts:390
t._invokeHandler @ rpcProtocol.ts:375
t._receiveRequest @ rpcProtocol.ts:295
t._receiveOneMessage @ rpcProtocol.ts:225
(anonymous) @ rpcProtocol.ts:100
e.fire @ event.ts:567
s @ ipc.net.ts:295
(anonymous) @ ipc.net.ts:302
e.fire @ event.ts:567
a @ ipc.net.ts:103
_socketDataListener @ ipc.net.ts:132
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636`

Also, thanks for a great extension!

**Comment by mukumugi** [comment]
Same issue here.
"TextEditor#edit not possible on closed editors"

It's a nice extension, hope the issue can be fixed.
Thanks!
